# Generated by Django 3.1.7 on 2021-03-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210306_0245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
